#Linux VM Deployment Of Static Application
name: Static Application Deploy To VM CI/CD

hosts: all
became: yes

on: 
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      -main

vars:
    server_name: ${{ secrets.HOST_IPV4_ADDRESS }}
    Username: ${{ secrets.HOST_USER_NAME }}
    Password: ${{ secrets.HOST_PASSWORD }}
    document_root: /var/www
    app_root: html_site

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update apt cache and install Nginx
        apt:
          name: nginx
          state: latest
          update_cache: yes 
      - name: Copy website files to the server's document root
        copy:
          src: "{{ app_root }}"
          dest: "{{ document_root }}"
          mode: preserve
      - name: Apply Nginx template
        template:
          src: files/nginx.conf.j2
          dest: /etc/nginx/sites-available/default
        notify: Restart Nginx
      - name: Enable new site
        file:
          src: /etc/nginx/sites-available/default
          dest: /etc/nginx/sites-enabled/default
          state: link
        notify: Restart Nginx
  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
